version: '3.7'
services:
  flask:
    image: flask-docker-nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app-volume:/tmp

  nginx:
    image: nginx:1.16
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app-volume:/tmp 

volumes:
  app-volume:
